-- ============================================================================
-- Migration Script: Change BUCKET_INSTANCE.ID from GENERATED ALWAYS to GENERATED BY DEFAULT
-- ============================================================================
-- This script modifies the existing BUCKET_INSTANCE table to allow explicit ID inserts
-- while still supporting auto-generation when IDs are not provided.
--
-- Usage:
--   sqlplus username/password@database @alter-bucket-identity.sql
-- ============================================================================

-- Oracle doesn't allow direct modification of identity column generation type
-- We need to drop and recreate the identity generation

-- Step 1: Drop the existing identity generation
ALTER TABLE BUCKET_INSTANCE MODIFY ID DROP IDENTITY;

-- Step 2: Add identity generation with BY DEFAULT option
ALTER TABLE BUCKET_INSTANCE MODIFY ID GENERATED BY DEFAULT AS IDENTITY
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    INCREMENT BY 1
    START WITH 1
    CACHE 20
    NOORDER
    NOCYCLE
    NOKEEP
    NOSCALE;

-- Verify the change
SELECT column_name, data_type, identity_column
FROM user_tab_columns
WHERE table_name = 'BUCKET_INSTANCE'
AND column_name = 'ID';

COMMIT;

-- ============================================================================
-- Migration Complete
-- ============================================================================
-- BUCKET_INSTANCE.ID now uses GENERATED BY DEFAULT AS IDENTITY
-- This allows:
--   - Explicit ID inserts when values are provided
--   - Auto-generation when ID is omitted from INSERT
-- ============================================================================
