-- ========================================================================
-- Database Initialization Script for SERVICE_INSTANCE and BUCKET_INSTANCE
-- Oracle Database SQL Script
-- ========================================================================

-- Drop existing sequences if they exist
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SERVICE_INSTANCE_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE AAA_USER_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

-- Drop existing tables if they exist (in correct order due to foreign keys)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE BUCKET_INSTANCE CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SERVICE_INSTANCE CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE AAA_USER CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

-- ========================================================================
-- Create AAA_USER Table
-- ========================================================================
CREATE TABLE AAA_USER (
    ID NUMBER(19,0) NOT NULL,
    USER_NAME VARCHAR2(64 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_AAA_USER PRIMARY KEY (ID),
    CONSTRAINT UK_AAA_USER_NAME UNIQUE (USER_NAME)
);

-- Create sequence for AAA_USER
CREATE SEQUENCE AAA_USER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ========================================================================
-- Create SERVICE_INSTANCE Table
-- ========================================================================
CREATE TABLE SERVICE_INSTANCE (
    ID NUMBER(19,0) NOT NULL,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    EXPIRY_DATE TIMESTAMP(6),
    IS_GROUP NUMBER(1,0),
    NEXT_CYCLE_START_DATE TIMESTAMP(6),
    PLAN_ID VARCHAR2(64 CHAR) NOT NULL,
    PLAN_NAME VARCHAR2(64 CHAR) NOT NULL,
    PLAN_TYPE VARCHAR2(64 CHAR) NOT NULL,
    RECURRING_FLAG NUMBER(1,0) NOT NULL,
    REQUEST_ID VARCHAR2(255 CHAR) NOT NULL,
    CYCLE_END_DATE TIMESTAMP(6),
    CYCLE_START_DATE TIMESTAMP(6),
    SERVICE_START_DATE TIMESTAMP(6) NOT NULL,
    STATUS VARCHAR2(64 CHAR) NOT NULL,
    UPDATED_AT TIMESTAMP(6) NOT NULL,
    USERNAME VARCHAR2(64 CHAR) NOT NULL,
    BILLING VARCHAR2(255 CHAR),
    CYCLE_DATE NUMBER(10,0),
    CONSTRAINT PK_SERVICE_INSTANCE PRIMARY KEY (ID),
    CONSTRAINT CHK_SI_IS_GROUP CHECK (IS_GROUP IN (0,1)),
    CONSTRAINT CHK_SI_RECURRING CHECK (RECURRING_FLAG IN (0,1)),
    CONSTRAINT FK_SI_USERNAME FOREIGN KEY (USERNAME) REFERENCES AAA_USER(USER_NAME)
);

-- Create sequence for SERVICE_INSTANCE
CREATE SEQUENCE SERVICE_INSTANCE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ========================================================================
-- Create BUCKET_INSTANCE Table
-- ========================================================================
CREATE TABLE BUCKET_INSTANCE (
    ID NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999
       INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL,
    BUCKET_ID VARCHAR2(64 CHAR) NOT NULL,
    BUCKET_TYPE VARCHAR2(255 CHAR),
    CARRY_FORWARD NUMBER(1,0) NOT NULL,
    CARRY_FORWARD_VALIDITY NUMBER(10,0),
    CONSUMPTION_LIMIT NUMBER(19,0),
    CONSUMPTION_LIMIT_WINDOW VARCHAR2(255 CHAR),
    CURRENT_BALANCE NUMBER(19,0) NOT NULL,
    EXPIRATION TIMESTAMP(6),
    INITIAL_BALANCE NUMBER(19,0),
    MAX_CARRY_FORWARD NUMBER(19,0),
    PRIORITY NUMBER(19,0) NOT NULL,
    RULE VARCHAR2(64 CHAR) NOT NULL,
    SERVICE_ID VARCHAR2(64 CHAR),
    SERVICE_INSTANCE_ID NUMBER(19,0),
    TIME_WINDOW VARCHAR2(64 CHAR) NOT NULL,
    TOTAL_CARRY_FORWARD NUMBER(19,0),
    USAGE NUMBER(19,0) NOT NULL,
    UPDATED_AT TIMESTAMP(6),
    IS_UNLIMITED NUMBER(38,0) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_BUCKET_INSTANCE PRIMARY KEY (ID),
    CONSTRAINT FK_BI_SERVICE_INSTANCE FOREIGN KEY (SERVICE_INSTANCE_ID) REFERENCES SERVICE_INSTANCE(ID)
);

-- ========================================================================
-- Insert Sample Data into AAA_USER
-- ========================================================================
INSERT INTO AAA_USER (ID, USER_NAME, CREATED_AT) VALUES (AAA_USER_SEQ.NEXTVAL, 'user001', SYSTIMESTAMP);
INSERT INTO AAA_USER (ID, USER_NAME, CREATED_AT) VALUES (AAA_USER_SEQ.NEXTVAL, 'user002', SYSTIMESTAMP);
INSERT INTO AAA_USER (ID, USER_NAME, CREATED_AT) VALUES (AAA_USER_SEQ.NEXTVAL, 'user003', SYSTIMESTAMP);
INSERT INTO AAA_USER (ID, USER_NAME, CREATED_AT) VALUES (AAA_USER_SEQ.NEXTVAL, 'user004', SYSTIMESTAMP);
INSERT INTO AAA_USER (ID, USER_NAME, CREATED_AT) VALUES (AAA_USER_SEQ.NEXTVAL, 'user005', SYSTIMESTAMP);
INSERT INTO AAA_USER (ID, USER_NAME, CREATED_AT) VALUES (AAA_USER_SEQ.NEXTVAL, 'user006', SYSTIMESTAMP);
INSERT INTO AAA_USER (ID, USER_NAME, CREATED_AT) VALUES (AAA_USER_SEQ.NEXTVAL, 'user007', SYSTIMESTAMP);
INSERT INTO AAA_USER (ID, USER_NAME, CREATED_AT) VALUES (AAA_USER_SEQ.NEXTVAL, 'user008', SYSTIMESTAMP);
INSERT INTO AAA_USER (ID, USER_NAME, CREATED_AT) VALUES (AAA_USER_SEQ.NEXTVAL, 'user009', SYSTIMESTAMP);
INSERT INTO AAA_USER (ID, USER_NAME, CREATED_AT) VALUES (AAA_USER_SEQ.NEXTVAL, 'user010', SYSTIMESTAMP);

-- ========================================================================
-- Insert SERVICE_INSTANCE Data (3 services per user = 30 total)
-- Distribution: yesterday(45%), today(40%), future(5%)
-- PLAN_IDs: 100COMBO182-192 (excluding 186)
-- ========================================================================

-- User001 - Service 1 (yesterday)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '365' DAY, 0, SYSTIMESTAMP + INTERVAL '30' DAY, '100COMBO182', 'Combo Plan 182', 'POSTPAID', 1, 'REQ-001-001', SYSTIMESTAMP + INTERVAL '30' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, 'ACTIVE', SYSTIMESTAMP, 'user001', 'MONTHLY', 1);

-- User001 - Service 2 (today)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '180' DAY, 0, SYSTIMESTAMP + INTERVAL '30' DAY, '100COMBO183', 'Combo Plan 183', 'PREPAID', 1, 'REQ-001-002', SYSTIMESTAMP + INTERVAL '30' DAY, SYSTIMESTAMP, SYSTIMESTAMP, 'ACTIVE', SYSTIMESTAMP, 'user001', 'PREPAY', 1);

-- User001 - Service 3 (yesterday)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP - INTERVAL '10' DAY, 1, NULL, '100COMBO184', 'Combo Plan 184', 'POSTPAID', 0, 'REQ-001-003', SYSTIMESTAMP + INTERVAL '30' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, 'EXPIRED', SYSTIMESTAMP, 'user001', 'MONTHLY', 2);

-- User002 - Service 1 (today)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '90' DAY, 0, SYSTIMESTAMP + INTERVAL '30' DAY, '100COMBO185', 'Combo Plan 185', 'POSTPAID', 1, 'REQ-002-001', SYSTIMESTAMP + INTERVAL '30' DAY, SYSTIMESTAMP, SYSTIMESTAMP, 'ACTIVE', SYSTIMESTAMP, 'user002', 'MONTHLY', 1);

-- User002 - Service 2 (yesterday)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '365' DAY, 0, SYSTIMESTAMP + INTERVAL '30' DAY, '100COMBO187', 'Combo Plan 187', 'PREPAID', 1, 'REQ-002-002', SYSTIMESTAMP + INTERVAL '30' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, 'ACTIVE', SYSTIMESTAMP, 'user002', 'PREPAY', 5);

-- User002 - Service 3 (yesterday)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '730' DAY, 0, SYSTIMESTAMP + INTERVAL '30' DAY, '100COMBO188', 'Combo Plan 188', 'POSTPAID', 1, 'REQ-002-003', SYSTIMESTAMP + INTERVAL '30' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, 'ACTIVE', SYSTIMESTAMP, 'user002', 'MONTHLY', 10);

-- User003 - Service 1 (future)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '400' DAY, 0, SYSTIMESTAMP + INTERVAL '35' DAY, '100COMBO189', 'Combo Plan 189', 'POSTPAID', 1, 'REQ-003-001', SYSTIMESTAMP + INTERVAL '35' DAY, SYSTIMESTAMP + INTERVAL '5' DAY, SYSTIMESTAMP + INTERVAL '5' DAY, 'PENDING', SYSTIMESTAMP, 'user003', 'MONTHLY', 1);

-- User003 - Service 2 (today)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '365' DAY, 0, SYSTIMESTAMP + INTERVAL '30' DAY, '100COMBO190', 'Combo Plan 190', 'PREPAID', 1, 'REQ-003-002', SYSTIMESTAMP + INTERVAL '30' DAY, SYSTIMESTAMP, SYSTIMESTAMP, 'ACTIVE', SYSTIMESTAMP, 'user003', 'PREPAY', 1);

-- User003 - Service 3 (yesterday)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '90' DAY, 0, SYSTIMESTAMP + INTERVAL '30' DAY, '100COMBO191', 'Combo Plan 191', 'POSTPAID', 1, 'REQ-003-003', SYSTIMESTAMP + INTERVAL '30' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, 'ACTIVE', SYSTIMESTAMP, 'user003', 'MONTHLY', 15);

-- User004 - Service 1 (yesterday)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '180' DAY, 0, SYSTIMESTAMP + INTERVAL '30' DAY, '100COMBO192', 'Combo Plan 192', 'PREPAID', 1, 'REQ-004-001', SYSTIMESTAMP + INTERVAL '30' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, 'ACTIVE', SYSTIMESTAMP, 'user004', 'PREPAY', 1);

-- User004 - Service 2 (today)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '365' DAY, 0, SYSTIMESTAMP + INTERVAL '30' DAY, '100COMBO182', 'Combo Plan 182', 'POSTPAID', 1, 'REQ-004-002', SYSTIMESTAMP + INTERVAL '30' DAY, SYSTIMESTAMP, SYSTIMESTAMP, 'ACTIVE', SYSTIMESTAMP, 'user004', 'MONTHLY', 1);

-- User004 - Service 3 (yesterday)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP - INTERVAL '5' DAY, 0, NULL, '100COMBO183', 'Combo Plan 183', 'PREPAID', 0, 'REQ-004-003', SYSTIMESTAMP - INTERVAL '5' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, 'EXPIRED', SYSTIMESTAMP, 'user004', 'PREPAY', 20);

-- User005 - Service 1 (today)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '365' DAY, 0, SYSTIMESTAMP + INTERVAL '30' DAY, '100COMBO184', 'Combo Plan 184', 'POSTPAID', 1, 'REQ-005-001', SYSTIMESTAMP + INTERVAL '30' DAY, SYSTIMESTAMP, SYSTIMESTAMP, 'ACTIVE', SYSTIMESTAMP, 'user005', 'MONTHLY', 1);

-- User005 - Service 2 (yesterday)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '180' DAY, 0, SYSTIMESTAMP + INTERVAL '30' DAY, '100COMBO185', 'Combo Plan 185', 'PREPAID', 1, 'REQ-005-002', SYSTIMESTAMP + INTERVAL '30' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, 'ACTIVE', SYSTIMESTAMP, 'user005', 'PREPAY', 5);

-- User005 - Service 3 (yesterday)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '90' DAY, 0, SYSTIMESTAMP + INTERVAL '30' DAY, '100COMBO187', 'Combo Plan 187', 'POSTPAID', 1, 'REQ-005-003', SYSTIMESTAMP + INTERVAL '30' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, 'ACTIVE', SYSTIMESTAMP, 'user005', 'MONTHLY', 10);

-- User006 - Service 1 (yesterday)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '365' DAY, 0, SYSTIMESTAMP + INTERVAL '30' DAY, '100COMBO188', 'Combo Plan 188', 'PREPAID', 1, 'REQ-006-001', SYSTIMESTAMP + INTERVAL '30' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, 'ACTIVE', SYSTIMESTAMP, 'user006', 'PREPAY', 1);

-- User006 - Service 2 (today)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '180' DAY, 0, SYSTIMESTAMP + INTERVAL '30' DAY, '100COMBO189', 'Combo Plan 189', 'POSTPAID', 1, 'REQ-006-002', SYSTIMESTAMP + INTERVAL '30' DAY, SYSTIMESTAMP, SYSTIMESTAMP, 'ACTIVE', SYSTIMESTAMP, 'user006', 'MONTHLY', 1);

-- User006 - Service 3 (yesterday)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '90' DAY, 0, SYSTIMESTAMP + INTERVAL '30' DAY, '100COMBO190', 'Combo Plan 190', 'PREPAID', 1, 'REQ-006-003', SYSTIMESTAMP + INTERVAL '30' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, 'ACTIVE', SYSTIMESTAMP, 'user006', 'PREPAY', 5);

-- User007 - Service 1 (today)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '365' DAY, 0, SYSTIMESTAMP + INTERVAL '30' DAY, '100COMBO191', 'Combo Plan 191', 'POSTPAID', 1, 'REQ-007-001', SYSTIMESTAMP + INTERVAL '30' DAY, SYSTIMESTAMP, SYSTIMESTAMP, 'ACTIVE', SYSTIMESTAMP, 'user007', 'MONTHLY', 1);

-- User007 - Service 2 (yesterday)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '180' DAY, 0, SYSTIMESTAMP + INTERVAL '30' DAY, '100COMBO192', 'Combo Plan 192', 'PREPAID', 1, 'REQ-007-002', SYSTIMESTAMP + INTERVAL '30' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, 'ACTIVE', SYSTIMESTAMP, 'user007', 'PREPAY', 5);

-- User007 - Service 3 (yesterday)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '90' DAY, 0, SYSTIMESTAMP + INTERVAL '30' DAY, '100COMBO182', 'Combo Plan 182', 'POSTPAID', 1, 'REQ-007-003', SYSTIMESTAMP + INTERVAL '30' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, 'ACTIVE', SYSTIMESTAMP, 'user007', 'MONTHLY', 10);

-- User008 - Service 1 (yesterday)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '365' DAY, 0, SYSTIMESTAMP + INTERVAL '30' DAY, '100COMBO183', 'Combo Plan 183', 'PREPAID', 1, 'REQ-008-001', SYSTIMESTAMP + INTERVAL '30' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, 'ACTIVE', SYSTIMESTAMP, 'user008', 'PREPAY', 1);

-- User008 - Service 2 (today)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '180' DAY, 0, SYSTIMESTAMP + INTERVAL '30' DAY, '100COMBO184', 'Combo Plan 184', 'POSTPAID', 1, 'REQ-008-002', SYSTIMESTAMP + INTERVAL '30' DAY, SYSTIMESTAMP, SYSTIMESTAMP, 'ACTIVE', SYSTIMESTAMP, 'user008', 'MONTHLY', 1);

-- User008 - Service 3 (yesterday)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP - INTERVAL '15' DAY, 0, NULL, '100COMBO185', 'Combo Plan 185', 'PREPAID', 0, 'REQ-008-003', SYSTIMESTAMP - INTERVAL '15' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, 'EXPIRED', SYSTIMESTAMP, 'user008', 'PREPAY', 15);

-- User009 - Service 1 (today)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '365' DAY, 0, SYSTIMESTAMP + INTERVAL '30' DAY, '100COMBO187', 'Combo Plan 187', 'POSTPAID', 1, 'REQ-009-001', SYSTIMESTAMP + INTERVAL '30' DAY, SYSTIMESTAMP, SYSTIMESTAMP, 'ACTIVE', SYSTIMESTAMP, 'user009', 'MONTHLY', 1);

-- User009 - Service 2 (yesterday)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '180' DAY, 0, SYSTIMESTAMP + INTERVAL '30' DAY, '100COMBO188', 'Combo Plan 188', 'PREPAID', 1, 'REQ-009-002', SYSTIMESTAMP + INTERVAL '30' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, 'ACTIVE', SYSTIMESTAMP, 'user009', 'PREPAY', 5);

-- User009 - Service 3 (yesterday)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '90' DAY, 0, SYSTIMESTAMP + INTERVAL '30' DAY, '100COMBO189', 'Combo Plan 189', 'POSTPAID', 1, 'REQ-009-003', SYSTIMESTAMP + INTERVAL '30' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, 'ACTIVE', SYSTIMESTAMP, 'user009', 'MONTHLY', 10);

-- User010 - Service 1 (yesterday)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '365' DAY, 0, SYSTIMESTAMP + INTERVAL '30' DAY, '100COMBO190', 'Combo Plan 190', 'PREPAID', 1, 'REQ-010-001', SYSTIMESTAMP + INTERVAL '30' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, SYSTIMESTAMP - INTERVAL '1' DAY, 'ACTIVE', SYSTIMESTAMP, 'user010', 'PREPAY', 1);

-- User010 - Service 2 (today)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '180' DAY, 0, SYSTIMESTAMP + INTERVAL '30' DAY, '100COMBO191', 'Combo Plan 191', 'POSTPAID', 1, 'REQ-010-002', SYSTIMESTAMP + INTERVAL '30' DAY, SYSTIMESTAMP, SYSTIMESTAMP, 'ACTIVE', SYSTIMESTAMP, 'user010', 'MONTHLY', 1);

-- User010 - Service 3 (future)
INSERT INTO SERVICE_INSTANCE (ID, CREATED_AT, EXPIRY_DATE, IS_GROUP, NEXT_CYCLE_START_DATE, PLAN_ID, PLAN_NAME, PLAN_TYPE, RECURRING_FLAG, REQUEST_ID, CYCLE_END_DATE, CYCLE_START_DATE, SERVICE_START_DATE, STATUS, UPDATED_AT, USERNAME, BILLING, CYCLE_DATE)
VALUES (SERVICE_INSTANCE_SEQ.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '400' DAY, 0, SYSTIMESTAMP + INTERVAL '37' DAY, '100COMBO192', 'Combo Plan 192', 'PREPAID', 1, 'REQ-010-003', SYSTIMESTAMP + INTERVAL '37' DAY, SYSTIMESTAMP + INTERVAL '7' DAY, SYSTIMESTAMP + INTERVAL '7' DAY, 'PENDING', SYSTIMESTAMP, 'user010', 'PREPAY', 1);

-- ========================================================================
-- Insert BUCKET_INSTANCE Data (Multiple buckets per service)
-- Dynamic values: BUCKET_ID, INITIAL_BALANCE > 9999999999, EXPIRATION
-- PRIORITY, RULE, TIME_WINDOW (00-08, 00-24, 00-18, 18-24), IS_UNLIMITED
-- ========================================================================

-- Buckets for Service 1 (user001-service1)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-001', 'DATA', 0, NULL, NULL, NULL, 45678901234, SYSTIMESTAMP + INTERVAL '30' DAY, 50000000000, NULL, 1, 'FIFO', 'SVC-001', 1, '00-24', NULL, 4321098766, SYSTIMESTAMP, 0);

INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-VOICE-001', 'VOICE', 1, 30, NULL, NULL, 15000000000, SYSTIMESTAMP + INTERVAL '30' DAY, 20000000000, 5000000000, 2, 'PRIORITY', 'SVC-001', 1, '00-08', NULL, 5000000000, SYSTIMESTAMP, 0);

-- Buckets for Service 2 (user001-service2)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-002', 'DATA', 0, NULL, 100000000000, 'DAILY', 98765432109, SYSTIMESTAMP + INTERVAL '90' DAY, 100000000000, NULL, 1, 'FIFO', 'SVC-002', 2, '00-24', NULL, 1234567891, SYSTIMESTAMP, 1);

INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-SMS-002', 'SMS', 1, 60, NULL, NULL, 9876543210, SYSTIMESTAMP + INTERVAL '90' DAY, 10000000000, 2000000000, 3, 'ROUND_ROBIN', 'SVC-002', 2, '18-24', NULL, 123456790, SYSTIMESTAMP, 0);

-- Buckets for Service 3 (user001-service3)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-003', 'DATA', 0, NULL, NULL, NULL, 0, SYSTIMESTAMP - INTERVAL '10' DAY, 30000000000, NULL, 1, 'FIFO', 'SVC-003', 3, '00-24', NULL, 30000000000, SYSTIMESTAMP, 0);

-- Buckets for Service 4 (user002-service1)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-004', 'DATA', 1, 90, NULL, NULL, 78901234567, SYSTIMESTAMP + INTERVAL '90' DAY, 80000000000, 10000000000, 1, 'WEIGHTED', 'SVC-004', 4, '00-18', NULL, 1098765433, SYSTIMESTAMP, 0);

INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-VOICE-004', 'VOICE', 0, NULL, NULL, NULL, 25000000000, SYSTIMESTAMP + INTERVAL '90' DAY, 25000000000, NULL, 2, 'FIFO', 'SVC-004', 4, '00-24', NULL, 0, SYSTIMESTAMP, 1);

-- Buckets for Service 5 (user002-service2)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-005', 'DATA', 0, NULL, NULL, NULL, 55555555555, SYSTIMESTAMP + INTERVAL '365' DAY, 60000000000, NULL, 1, 'PRIORITY', 'SVC-005', 5, '00-24', NULL, 4444444445, SYSTIMESTAMP, 0);

INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-SMS-005', 'SMS', 1, 30, NULL, NULL, 18000000000, SYSTIMESTAMP + INTERVAL '365' DAY, 20000000000, 5000000000, 3, 'FIFO', 'SVC-005', 5, '18-24', NULL, 2000000000, SYSTIMESTAMP, 0);

-- Buckets for Service 6 (user002-service3)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-006', 'DATA', 0, NULL, 200000000000, 'WEEKLY', 125000000000, SYSTIMESTAMP + INTERVAL '730' DAY, 150000000000, NULL, 1, 'ROUND_ROBIN', 'SVC-006', 6, '00-08', NULL, 25000000000, SYSTIMESTAMP, 1);

-- Buckets for Service 7 (user003-service1)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-007', 'DATA', 1, 60, NULL, NULL, 40000000000, SYSTIMESTAMP + INTERVAL '400' DAY, 40000000000, 10000000000, 1, 'FIFO', 'SVC-007', 7, '00-24', NULL, 0, SYSTIMESTAMP, 0);

INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-VOICE-007', 'VOICE', 0, NULL, NULL, NULL, 35000000000, SYSTIMESTAMP + INTERVAL '400' DAY, 35000000000, NULL, 2, 'WEIGHTED', 'SVC-007', 7, '00-18', NULL, 0, SYSTIMESTAMP, 0);

-- Buckets for Service 8 (user003-service2)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-008', 'DATA', 0, NULL, NULL, NULL, 88888888888, SYSTIMESTAMP + INTERVAL '365' DAY, 90000000000, NULL, 1, 'PRIORITY', 'SVC-008', 8, '00-24', NULL, 1111111112, SYSTIMESTAMP, 1);

-- Buckets for Service 9 (user003-service3)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-009', 'DATA', 1, 45, NULL, NULL, 65000000000, SYSTIMESTAMP + INTERVAL '90' DAY, 70000000000, 15000000000, 1, 'FIFO', 'SVC-009', 9, '18-24', NULL, 5000000000, SYSTIMESTAMP, 0);

INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-SMS-009', 'SMS', 0, NULL, NULL, NULL, 12000000000, SYSTIMESTAMP + INTERVAL '90' DAY, 12000000000, NULL, 3, 'ROUND_ROBIN', 'SVC-009', 9, '00-24', NULL, 0, SYSTIMESTAMP, 0);

-- Buckets for Service 10 (user004-service1)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-010', 'DATA', 0, NULL, NULL, NULL, 33333333333, SYSTIMESTAMP + INTERVAL '180' DAY, 35000000000, NULL, 1, 'WEIGHTED', 'SVC-010', 10, '00-08', NULL, 1666666667, SYSTIMESTAMP, 0);

-- Buckets for remaining services (11-30)
-- Service 11 (user004-service2)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-011', 'DATA', 1, 90, NULL, NULL, 77777777777, SYSTIMESTAMP + INTERVAL '365' DAY, 80000000000, 20000000000, 1, 'FIFO', 'SVC-011', 11, '00-24', NULL, 2222222223, SYSTIMESTAMP, 1);

-- Service 12 (user004-service3)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-012', 'DATA', 0, NULL, NULL, NULL, 0, SYSTIMESTAMP - INTERVAL '5' DAY, 25000000000, NULL, 1, 'PRIORITY', 'SVC-012', 12, '00-18', NULL, 25000000000, SYSTIMESTAMP, 0);

-- Service 13 (user005-service1)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-013', 'DATA', 1, 30, NULL, NULL, 48000000000, SYSTIMESTAMP + INTERVAL '365' DAY, 50000000000, 10000000000, 1, 'ROUND_ROBIN', 'SVC-013', 13, '18-24', NULL, 2000000000, SYSTIMESTAMP, 0);

INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-VOICE-013', 'VOICE', 0, NULL, NULL, NULL, 22000000000, SYSTIMESTAMP + INTERVAL '365' DAY, 22000000000, NULL, 2, 'FIFO', 'SVC-013', 13, '00-24', NULL, 0, SYSTIMESTAMP, 0);

-- Service 14 (user005-service2)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-014', 'DATA', 0, NULL, 150000000000, 'MONTHLY', 95000000000, SYSTIMESTAMP + INTERVAL '180' DAY, 100000000000, NULL, 1, 'WEIGHTED', 'SVC-014', 14, '00-08', NULL, 5000000000, SYSTIMESTAMP, 1);

-- Service 15 (user005-service3)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-015', 'DATA', 1, 60, NULL, NULL, 58000000000, SYSTIMESTAMP + INTERVAL '90' DAY, 60000000000, 12000000000, 1, 'PRIORITY', 'SVC-015', 15, '00-24', NULL, 2000000000, SYSTIMESTAMP, 0);

-- Service 16 (user006-service1)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-016', 'DATA', 0, NULL, NULL, NULL, 44444444444, SYSTIMESTAMP + INTERVAL '365' DAY, 45000000000, NULL, 1, 'FIFO', 'SVC-016', 16, '00-18', NULL, 555555556, SYSTIMESTAMP, 0);

INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-SMS-016', 'SMS', 1, 45, NULL, NULL, 16000000000, SYSTIMESTAMP + INTERVAL '365' DAY, 18000000000, 5000000000, 3, 'ROUND_ROBIN', 'SVC-016', 16, '18-24', NULL, 2000000000, SYSTIMESTAMP, 0);

-- Service 17 (user006-service2)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-017', 'DATA', 0, NULL, NULL, NULL, 72000000000, SYSTIMESTAMP + INTERVAL '180' DAY, 75000000000, NULL, 1, 'WEIGHTED', 'SVC-017', 17, '00-24', NULL, 3000000000, SYSTIMESTAMP, 1);

-- Service 18 (user006-service3)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-018', 'DATA', 1, 90, NULL, NULL, 38000000000, SYSTIMESTAMP + INTERVAL '90' DAY, 40000000000, 8000000000, 1, 'PRIORITY', 'SVC-018', 18, '00-08', NULL, 2000000000, SYSTIMESTAMP, 0);

-- Service 19 (user007-service1)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-019', 'DATA', 0, NULL, 100000000000, 'DAILY', 67890123456, SYSTIMESTAMP + INTERVAL '365' DAY, 70000000000, NULL, 1, 'FIFO', 'SVC-019', 19, '18-24', NULL, 2109876544, SYSTIMESTAMP, 1);

-- Service 20 (user007-service2)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-020', 'DATA', 1, 30, NULL, NULL, 52000000000, SYSTIMESTAMP + INTERVAL '180' DAY, 55000000000, 10000000000, 1, 'ROUND_ROBIN', 'SVC-020', 20, '00-24', NULL, 3000000000, SYSTIMESTAMP, 0);

INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-VOICE-020', 'VOICE', 0, NULL, NULL, NULL, 28000000000, SYSTIMESTAMP + INTERVAL '180' DAY, 28000000000, NULL, 2, 'WEIGHTED', 'SVC-020', 20, '00-18', NULL, 0, SYSTIMESTAMP, 0);

-- Service 21 (user007-service3)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-021', 'DATA', 0, NULL, NULL, NULL, 42000000000, SYSTIMESTAMP + INTERVAL '90' DAY, 45000000000, NULL, 1, 'PRIORITY', 'SVC-021', 21, '00-24', NULL, 3000000000, SYSTIMESTAMP, 0);

-- Service 22 (user008-service1)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-022', 'DATA', 1, 60, NULL, NULL, 61000000000, SYSTIMESTAMP + INTERVAL '365' DAY, 65000000000, 15000000000, 1, 'FIFO', 'SVC-022', 22, '00-08', NULL, 4000000000, SYSTIMESTAMP, 1);

-- Service 23 (user008-service2)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-023', 'DATA', 0, NULL, 200000000000, 'WEEKLY', 82000000000, SYSTIMESTAMP + INTERVAL '180' DAY, 85000000000, NULL, 1, 'ROUND_ROBIN', 'SVC-023', 23, '18-24', NULL, 3000000000, SYSTIMESTAMP, 0);

INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-SMS-023', 'SMS', 1, 30, NULL, NULL, 19000000000, SYSTIMESTAMP + INTERVAL '180' DAY, 20000000000, 3000000000, 3, 'WEIGHTED', 'SVC-023', 23, '00-24', NULL, 1000000000, SYSTIMESTAMP, 0);

-- Service 24 (user008-service3)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-024', 'DATA', 0, NULL, NULL, NULL, 0, SYSTIMESTAMP - INTERVAL '15' DAY, 32000000000, NULL, 1, 'PRIORITY', 'SVC-024', 24, '00-18', NULL, 32000000000, SYSTIMESTAMP, 0);

-- Service 25 (user009-service1)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-025', 'DATA', 1, 45, NULL, NULL, 73000000000, SYSTIMESTAMP + INTERVAL '365' DAY, 75000000000, 18000000000, 1, 'FIFO', 'SVC-025', 25, '00-24', NULL, 2000000000, SYSTIMESTAMP, 1);

-- Service 26 (user009-service2)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-026', 'DATA', 0, NULL, NULL, NULL, 47000000000, SYSTIMESTAMP + INTERVAL '180' DAY, 50000000000, NULL, 1, 'ROUND_ROBIN', 'SVC-026', 26, '00-08', NULL, 3000000000, SYSTIMESTAMP, 0);

INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-VOICE-026', 'VOICE', 1, 60, NULL, NULL, 31000000000, SYSTIMESTAMP + INTERVAL '180' DAY, 33000000000, 8000000000, 2, 'WEIGHTED', 'SVC-026', 26, '18-24', NULL, 2000000000, SYSTIMESTAMP, 0);

-- Service 27 (user009-service3)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-027', 'DATA', 0, NULL, 180000000000, 'MONTHLY', 56000000000, SYSTIMESTAMP + INTERVAL '90' DAY, 60000000000, NULL, 1, 'PRIORITY', 'SVC-027', 27, '00-24', NULL, 4000000000, SYSTIMESTAMP, 0);

-- Service 28 (user010-service1)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-028', 'DATA', 1, 90, NULL, NULL, 89000000000, SYSTIMESTAMP + INTERVAL '365' DAY, 90000000000, 20000000000, 1, 'FIFO', 'SVC-028', 28, '00-18', NULL, 1000000000, SYSTIMESTAMP, 1);

-- Service 29 (user010-service2)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-029', 'DATA', 0, NULL, NULL, NULL, 64000000000, SYSTIMESTAMP + INTERVAL '180' DAY, 65000000000, NULL, 1, 'ROUND_ROBIN', 'SVC-029', 29, '00-24', NULL, 1000000000, SYSTIMESTAMP, 0);

INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-SMS-029', 'SMS', 1, 30, NULL, NULL, 24000000000, SYSTIMESTAMP + INTERVAL '180' DAY, 25000000000, 6000000000, 3, 'WEIGHTED', 'SVC-029', 29, '00-08', NULL, 1000000000, SYSTIMESTAMP, 0);

-- Service 30 (user010-service3)
INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-DATA-030', 'DATA', 0, NULL, NULL, NULL, 50000000000, SYSTIMESTAMP + INTERVAL '400' DAY, 50000000000, NULL, 1, 'PRIORITY', 'SVC-030', 30, '18-24', NULL, 0, SYSTIMESTAMP, 0);

INSERT INTO BUCKET_INSTANCE (BUCKET_ID, BUCKET_TYPE, CARRY_FORWARD, CARRY_FORWARD_VALIDITY, CONSUMPTION_LIMIT, CONSUMPTION_LIMIT_WINDOW, CURRENT_BALANCE, EXPIRATION, INITIAL_BALANCE, MAX_CARRY_FORWARD, PRIORITY, RULE, SERVICE_ID, SERVICE_INSTANCE_ID, TIME_WINDOW, TOTAL_CARRY_FORWARD, USAGE, UPDATED_AT, IS_UNLIMITED)
VALUES ('BUCKET-VOICE-030', 'VOICE', 1, 60, NULL, NULL, 36000000000, SYSTIMESTAMP + INTERVAL '400' DAY, 38000000000, 10000000000, 2, 'FIFO', 'SVC-030', 30, '00-24', NULL, 2000000000, SYSTIMESTAMP, 0);

-- ========================================================================
-- Commit the transaction
-- ========================================================================
COMMIT;

-- ========================================================================
-- Summary Report
-- ========================================================================
SELECT 'AAA_USER Table: ' || COUNT(*) || ' users created' AS Summary FROM AAA_USER
UNION ALL
SELECT 'SERVICE_INSTANCE Table: ' || COUNT(*) || ' services created (3 per user)' FROM SERVICE_INSTANCE
UNION ALL
SELECT 'BUCKET_INSTANCE Table: ' || COUNT(*) || ' buckets created' FROM BUCKET_INSTANCE;
